version: '3'
services:
  flaskapp:
    build: . 
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=practise
volumes:
  postgres_data:


