"""all

Revision ID: bb3bf404eb2b
Revises: e54bfa425818
Create Date: 2023-07-25 18:50:31.928879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3bf404eb2b'
down_revision = 'e54bfa425818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=10000), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=10000), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
