"""all

Revision ID: e54bfa425818
Revises: 9f50e381f85a
Create Date: 2023-07-25 18:48:18.319399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54bfa425818'
down_revision = '9f50e381f85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Integer(), nullable=True))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.INTEGER(), nullable=True))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
